# Basics of TensorFlow

### Introduction to Tensors

In [1]:
import tensorflow as tf
import numpy as np
print (tf.__version__)

2.8.2


In [4]:
## Create Tensorflow with tf.constant()
scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check number of dimensions
scalar.ndim

0

In [6]:
# Create vector
vector= tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
# Create matrix
matrix= tf.constant ([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim 

2

In [10]:
from numpy import float16
#Create matrix with floating point numbers
matrix_2= tf.constant ([[10.0,7],
                     [7.0,10]], dtype=float16)
matrix_2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float16)>

### Creating tensors with `tf.variable`

In [11]:
tf.Variable 

tensorflow.python.ops.variables.Variable

In [12]:
changeable_tensor= tf.Variable([10,7])
unchangeable_tensor= tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
changeable_tensor[0]= 7

TypeError: ignored

In [14]:
# Assigning a new value to an index in a variable tensor
changeable_tensor[0].assign(7)
changeable_tensor
#unchangeable tensor can not be changed.

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensors.


In [15]:
# A random tensor has an arbitrary shape with random numbers in it
random_Tensor= tf.random.uniform(shape=(3,2)) 
random_Tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6008359 , 0.35944772],
       [0.33842027, 0.09553361],
       [0.6283134 , 0.09709775]], dtype=float32)>

In [16]:
random_Tensor= tf.random.Generator.from_seed(42)
random_Tensor= random_Tensor.normal(shape=(3,2))
random_Tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

### Shuffling the order of tensors

In [17]:
# Valuable when you want to shuffle your tensor
not_shuffled = tf.constant([[10,7],
                            [3,2],
                            [4,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 4,  5]], dtype=int32)>

In [18]:
# Shuffling the tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 4,  5]], dtype=int32)>

### Creating tensors from numpy arrays.

In [19]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [21]:

# Tensors can be run much faster on a GPU
numpy_A= np.arange(1,25, dtype= 'int32')
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A= tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [23]:
B= tf.constant(numpy_A, shape=(2,3,4)) #Reshaping the numpy array when converting it to a tensor
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [24]:
A.ndim

1

### Getting information from your tensors.

* Shape
* Rank
* Axis or Dimension
* Size


In [25]:
# Create a rank 4 dimensions (4 dimensions)

rank_4_tensor= tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [27]:
rank_4_tensor.dtype

tf.float32

### Indexing Tensor

In [28]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
rank_4_tensor[0][0][0]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [31]:
rank_4_tensor[0][0][0].shape


TensorShape([5])

In [32]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [33]:
rank_4_tensor[:1,:1,:,:1].shape

TensorShape([1, 1, 4, 1])

In [34]:
# Adding a dimension to a tensor.

rankTwoTensor= tf.constant([[10,7],
                            [2,3]])

In [35]:
rankTwoTensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [36]:
# Add in an extra dimension to the Rank 2 tensor
rankThreeTensor= rankTwoTensor[tf.newaxis, ...]
rankThreeTensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 2,  3]]], dtype=int32)>

In [37]:
rankThreeTensorTwo= rankTwoTensor[..., tf.newaxis]
rankThreeTensorTwo

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [38]:
#Alternative to tf.newaxis

tf.expand_dims(rankTwoTensor, axis=-1) # final axis is being expanded by 1


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 3]]], dtype=int32)>

### Manipulating tensors (Basic Tensor Operations)

In [39]:
tensorA= tf.constant([[10,7],
                      [3,4]])
#tensorA+=10 #Changes the original tensor
tensorA+10 #does not change the original tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [40]:
tensorA*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [41]:
tensorA-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [42]:
tf.multiply(tensorA,10) #faster as compared to traditional operations


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In [43]:
tf.linalg.matmul(tensorA, tensorA)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [44]:
tensorA @ tensorA


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [45]:
tf.matmul(tensorA, tf.transpose(tensorA))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[149,  58],
       [ 58,  25]], dtype=int32)>

**Dot Product**

In [46]:
X= tf.constant([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [47]:
Y= tf.constant([[7,8,9],
                [10,11,12],
                [13,14,15]])

In [48]:
tf.tensordot(X,Y, axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 66,  72,  78],
       [156, 171, 186],
       [246, 270, 294]], dtype=int32)>

**Changing the data type of tensor values**

In [49]:
B= tf.constant([1.7, 1.4])
C= tf.constant([1, 4])
B.dtype, C.dtype

(tf.float32, tf.int32)

**In Tf by default the precision is 32 bits, but reducing it to a lower accuracy improves computation cost and thereby training time**

In [50]:
B= tf.cast(B, dtype= 'float16')
B.dtype

tf.float16

In [51]:
E= tf.cast(C, dtype='float32')
C.dtype, E.dtype

(tf.int32, tf.float32)

### Aggregating Tensors

Condensing multiple values down to a smaller amount of values.

In [52]:
# Get absolute values
X= -X
X

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]], dtype=int32)>

In [53]:
Y= tf.abs(X)
Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [54]:
D= tf.constant([[1, 9, -1],
                [2, 7, -3],
                [12, -1, 0.5]])
D

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1. ,  9. , -1. ],
       [ 2. ,  7. , -3. ],
       [12. , -1. ,  0.5]], dtype=float32)>

In [55]:
DE= tf.constant(np.random.randint(0, 100, 69))
DE

<tf.Tensor: shape=(69,), dtype=int64, numpy=
array([39, 81, 24, 73, 11, 47, 76, 10, 97, 52, 25,  0, 71, 70, 36, 68, 85,
       12, 58, 50, 12, 58, 17,  7, 75, 22, 37, 58, 31,  7, 19, 12, 50, 85,
       30, 52,  1,  8, 88, 53, 24, 52, 68, 65, 35, 90,  6, 77, 57, 96, 62,
       49, 11, 35, 69, 93, 11, 32, 35, 94, 90, 40, 43, 97, 62, 27, 56, 96,
       70])>

In [56]:
tf.size(DE), DE.shape, DE.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=69>, TensorShape([69]), 1)

In [57]:
tf.reduce_min(DE) #minimum value in tensor  

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [58]:
tf.reduce_max(DE) #maximum value in tensor

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [59]:
tf.reduce_sum(DE)

<tf.Tensor: shape=(), dtype=int64, numpy=3349>

In [60]:
standardDeviation= tf.math.reduce_std(tf.cast(DE, dtype='float32'))
standardDeviation

<tf.Tensor: shape=(), dtype=float32, numpy=28.615685>

In [61]:
variance= standardDeviation**2
variance

<tf.Tensor: shape=(), dtype=float32, numpy=818.8574>

In [62]:
import tensorflow_probability as tfp #Alternatively to find variance we can also use tensorflow probability.
tfp.stats.variance(DE)

<tf.Tensor: shape=(), dtype=int64, numpy=819>

In [65]:
#Also
tf.math.reduce_variance(tf.cast(DE, dtype='float32'))

<tf.Tensor: shape=(), dtype=float32, numpy=818.8574>

* Find the positional minimum in a tensor
* Find the positional maximum in a tensor

In [68]:
DE= tf.constant(np.random.uniform(size=50)) #generate a numpy array with uniform random distribution
DE

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.88326123, 0.92126208, 0.9329751 , 0.78614152, 0.02125145,
       0.20223752, 0.57319384, 0.24967534, 0.52691583, 0.23590651,
       0.54368291, 0.64058284, 0.84308571, 0.42052139, 0.16382491,
       0.92833813, 0.15342   , 0.75694912, 0.87980356, 0.14707254,
       0.92922029, 0.02819275, 0.86511501, 0.28631227, 0.96129025,
       0.6740822 , 0.74495006, 0.95965687, 0.48184294, 0.40196304,
       0.41853685, 0.13234221, 0.67157452, 0.23259044, 0.33264184,
       0.87792461, 0.69309545, 0.37683744, 0.96293541, 0.15374669,
       0.5922901 , 0.35423086, 0.77318007, 0.43416616, 0.56248301,
       0.74414507, 0.39262749, 0.71780843, 0.8993214 , 0.2535055 ])>

In [71]:
maxIndex=tf.argmax(DE)

In [74]:
print( DE[maxIndex]==tf.reduce_max(DE))

tf.Tensor(True, shape=(), dtype=bool)


In [78]:
### Squeezing a tensor

G= tf.constant(tf.random.uniform(shape= [50,2]), shape= (1,2,1,1,50))
G

<tf.Tensor: shape=(1, 2, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.5157511 , 0.01197624, 0.7862716 , 0.32361662, 0.30716908,
           0.46964633, 0.547125  , 0.3935356 , 0.39774525, 0.0659616 ,
           0.10503626, 0.90877044, 0.21793664, 0.19877553, 0.42342138,
           0.60996723, 0.47242415, 0.50644624, 0.08501947, 0.70703125,
           0.15317464, 0.5784581 , 0.46170008, 0.664613  , 0.1498226 ,
           0.4418497 , 0.24854803, 0.69830096, 0.9109111 , 0.737594  ,
           0.8457786 , 0.619195  , 0.33586013, 0.8366617 , 0.74716854,
           0.5780866 , 0.80185986, 0.8741784 , 0.33909225, 0.409014  ,
           0.0976938 , 0.80359983, 0.41268265, 0.842065  , 0.49727416,
           0.9033539 , 0.06802237, 0.00334668, 0.14503741, 0.27217507]]],


        [[[0.32298505, 0.02639723, 0.05296671, 0.68126714, 0.7506492 ,
           0.7390492 , 0.43067145, 0.6646013 , 0.11300814, 0.67444646,
           0.90667033, 0.47810447, 0.2667035 , 0.36673415, 0.03435206,
           0.7

In [79]:
G_squeezed= tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(2, 50), dtype=float32, numpy=
 array([[0.5157511 , 0.01197624, 0.7862716 , 0.32361662, 0.30716908,
         0.46964633, 0.547125  , 0.3935356 , 0.39774525, 0.0659616 ,
         0.10503626, 0.90877044, 0.21793664, 0.19877553, 0.42342138,
         0.60996723, 0.47242415, 0.50644624, 0.08501947, 0.70703125,
         0.15317464, 0.5784581 , 0.46170008, 0.664613  , 0.1498226 ,
         0.4418497 , 0.24854803, 0.69830096, 0.9109111 , 0.737594  ,
         0.8457786 , 0.619195  , 0.33586013, 0.8366617 , 0.74716854,
         0.5780866 , 0.80185986, 0.8741784 , 0.33909225, 0.409014  ,
         0.0976938 , 0.80359983, 0.41268265, 0.842065  , 0.49727416,
         0.9033539 , 0.06802237, 0.00334668, 0.14503741, 0.27217507],
        [0.32298505, 0.02639723, 0.05296671, 0.68126714, 0.7506492 ,
         0.7390492 , 0.43067145, 0.6646013 , 0.11300814, 0.67444646,
         0.90667033, 0.47810447, 0.2667035 , 0.36673415, 0.03435206,
         0.74413157, 0.41719544, 0.64220643, 0.65857

### One hot encoding

In [81]:
some_list= [0,1,2,3]
# One hot encode our list of indices

tf.one_hot(some_list, depth = 4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [82]:
tf.one_hot(some_list, depth = 5)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [84]:
some_listTwo = tf.constant([0, 1, 1 , 2, 3, 2])
tf.one_hot(some_listTwo, depth= 6)

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.]], dtype=float32)>

In [86]:
## Squaring, log, square root

H= tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [87]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [90]:
tf.sqrt(tf.cast(H, dtype='float32'))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [93]:
tf.math.log(tf.cast(H, dtype='float32'))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

In [94]:
J= tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [95]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

**The default type of a tensor created from numpy array is float64 and a tensor created through a python list or tensorflow is float32**

### Finding access to GPUs

In [2]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
!nvidia-smi

Mon Jun  6 17:49:09 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------